# keeping this minimal to stay flexible for all systems
# general
set -g extended-keys on
set -g extended-keys-format csi-u
set -g mouse on
set -g status-position top
set -g default-terminal "tmux-256color"
set -g renumber-windows on
set -g base-index 1
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
set -g allow-rename off

# appearance
set -g status-style bg=colour236
set -g status-left "#[fg=brightwhite]#S "
set -g status-right ""
set -g window-status-style fg=brightwhite
set -g window-status-current-style fg=black,bg=colour198
set -g pane-active-border-style fg=colour198
set -g pane-border-style fg=colour236
